/* Digital Filter Coefficients Generated by Python */
#ifndef FILTERS_H
#define FILTERS_H

const float B_BPF[4] = { -0.00000000f, 0.17599559f, -0.37731663f, 0.18956969f };
const float A_BPF[5] = { 1.00000000f, -1.99929403f, 2.18137031f, -1.24309247f, 0.41124070f };

const float B_LPF[2] = { 0.00000000f, 0.42313325f };
const float A_LPF[3] = { 1.00000000f, -0.80731372f, 0.26372065f };

#endif // FILTERS_H
